[09/Oct/2012 14:16:29 +0000] upload       ERROR    Failed to remove temporary upload file "/tmp/hue-uploads/tmp.93.180.198.35.7444402123417560915". Please cleanup manually: Delete failed: /tmp/hue-uploads/tmp.93.180.198.35.7444402123417560915
Traceback (most recent call last):
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/upload.py", line 96, in remove
    self._fs.remove(self._path)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 226, in remove
    self._delete(path, recursive=False)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 222, in _delete
    raise IOError('Delete failed: %s' % (smart_str(path),))
IOError: Delete failed: /tmp/hue-uploads/tmp.93.180.198.35.7444402123417560915
[09/Oct/2012 14:22:40 +0000] upload       ERROR    Failed to remove temporary upload file "/tmp/hue-uploads/tmp.93.180.198.35.7944233665823993527". Please cleanup manually: Delete failed: /tmp/hue-uploads/tmp.93.180.198.35.7944233665823993527
Traceback (most recent call last):
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/upload.py", line 96, in remove
    self._fs.remove(self._path)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 226, in remove
    self._delete(path, recursive=False)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 222, in _delete
    raise IOError('Delete failed: %s' % (smart_str(path),))
IOError: Delete failed: /tmp/hue-uploads/tmp.93.180.198.35.7944233665823993527
[09/Oct/2012 14:22:41 +0000] upload       ERROR    Left-over upload file is not cleaned up: /tmp/hue-uploads/tmp.93.180.198.35.7944233665823993527
[09/Oct/2012 14:43:20 +0000] upload       ERROR    Left-over upload file is not cleaned up: /tmp/hue-uploads/tmp.93.180.198.35.7444402123417560915
[11/Oct/2012 10:34:33 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/apps/beeswax/src/beeswax/../../gen-py/beeswaxd/BeeswaxService.py", line 286, in get_state
    return self.recv_get_state()
  File "/home/hue/hue/apps/beeswax/src/beeswax/../../gen-py/beeswaxd/BeeswaxService.py", line 309, in recv_get_state
    raise result.error
QueryNotFoundException: QueryNotFoundException()
[11/Oct/2012 10:35:03 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 10:37:34 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 10:38:39 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 10:42:41 +0000] upload       ERROR    Failed to remove temporary upload file "/tmp/hue-uploads/tmp.46.211.12.176.17547621581861300708". Please cleanup manually: Delete failed: /tmp/hue-uploads/tmp.46.211.12.176.17547621581861300708
Traceback (most recent call last):
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/upload.py", line 96, in remove
    self._fs.remove(self._path)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 226, in remove
    self._delete(path, recursive=False)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 222, in _delete
    raise IOError('Delete failed: %s' % (smart_str(path),))
IOError: Delete failed: /tmp/hue-uploads/tmp.46.211.12.176.17547621581861300708
[11/Oct/2012 10:43:43 +0000] upload       ERROR    Left-over upload file is not cleaned up: /tmp/hue-uploads/tmp.46.211.12.176.17547621581861300708
[11/Oct/2012 10:47:21 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 10:50:13 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 10:51:49 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 11:01:47 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:16:58 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:17:02 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:17:16 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:47:28 +0000] upload       ERROR    Failed to remove temporary upload file "/tmp/hue-uploads/tmp.46.211.12.176.1315633946306948676". Please cleanup manually: Delete failed: /tmp/hue-uploads/tmp.46.211.12.176.1315633946306948676
Traceback (most recent call last):
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/upload.py", line 96, in remove
    self._fs.remove(self._path)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 226, in remove
    self._delete(path, recursive=False)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", line 222, in _delete
    raise IOError('Delete failed: %s' % (smart_str(path),))
IOError: Delete failed: /tmp/hue-uploads/tmp.46.211.12.176.1315633946306948676
[11/Oct/2012 12:49:46 +0000] upload       ERROR    Left-over upload file is not cleaned up: /tmp/hue-uploads/tmp.46.211.12.176.1315633946306948676
[11/Oct/2012 12:54:05 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:54:09 +0000] upload       ERROR    Left-over upload file is not cleaned up: /tmp/hue-uploads/tmp.95.81.39.48.14029500191714579775
[11/Oct/2012 12:54:10 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:54:32 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:54:32 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 12:56:35 +0000] thrift_util  ERROR    Thrift saw exception (this may be expected).
Traceback (most recent call last):
  File "/home/hue/hue/desktop/core/src/desktop/lib/thrift_util.py", line 340, in wrapper
    ret = res(*args, **kwargs)
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 394, in getJob
    return self.recv_getJob()
  File "/home/hue/hue/desktop/libs/hadoop/src/hadoop/../../gen-py/hadoop/api/jobtracker/Jobtracker.py", line 418, in recv_getJob
    raise result.err
JobNotFoundException: JobNotFoundException()
[11/Oct/2012 13:12:15 +0000] upload       ERROR    Left-over upload file is not cleaned up: /tmp/hue-uploads/tmp.95.81.39.48.6944451212691381200
